apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: proyectofinal-auto-scaler
spec:  
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: proyectofinal-dpl
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleDown:
      selectPolicy: Min 
      stabilizationWindowSeconds: 10
    scaleUp: 
      selectPolicy: Max
      stabilizationWindowSeconds: 10