apiVersion: apps/v1
kind: Deployment
metadata:
  name: proyectofinal-dpl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proyectofinal
  template:
    metadata:
      labels:
        app: proyectofinal
    spec:
      containers:
        - name: proyectofinal
          image: diegoac0/proyecto-final:1.0.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
             
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: proyectofinal-svc
spec:
  selector:
    app: proyectofinal
  ports:
    - port: 8081
      targetPort: 8080
  type: LoadBalancer

