name: SecDevOps

on: [push, pull_request]

jobs:

  analizar-secretos:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      #- name: Check secrets
        #run: docker run --rm -v "$(pwd):/proj" dxa4481/trufflehog --regex -x .trufflehogignore  --max_depth=1 file:///proj

  prueba-sast:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Configurar CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: 'java'
    #- name: Autobuild
      #uses: github/codeql-action/autobuild@v1
    #- name: Ejecutar CodeQL
      #uses: github/codeql-action/analyze@v1

  construir-imagen-docker:
    needs: [analizar-secretos, prueba-sast]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Construir imagen Docker
        run: docker build -t alberto1118/app-notas:1.0.0 .


  prueba-dast:
    needs: construir-imagen-docker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Ejecutar mi imagen
        run: docker run --rm --detach --publish 8080:8080 --name app-notas alberto1118/app-notas:1.0.0
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: 'http://localhost:8080'
        
  subir-imagen-docker:
    needs: construir-imagen-docker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Loguarse a DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Construir imagen Docker
        run: docker build -t alberto1118/app-notas:1.0.0 .
      - name: Publicar la imagen a DockerHub
        run: docker push alberto1118/app-notas:1.0.0
        
        
  desplegar-app:
    needs: subir-imagen-docker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: tfm-alberto-devops
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true