name: DevOps

on: [push, pull_request]

jobs:
  construirImagen:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Construir imagen Docker
        run: docker build -t alberto1118/app-notas:1.0.0 .
        
  subirImagen:
    needs: construirImagen
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Loguarse a DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Publicar la imagen a DockerHub
        run: docker push alberto1118/app-notas:1.0.0