name: DevOps

on: [push, pull_request]

jobs:
  construir-imagen:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Construir imagen Docker
        run: docker build -t alberto1118/app-notas:1.0.0 .
        
  subir-imagen:
    needs: construirImagen
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Loguarse a DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Construir imagen Docker
        run: docker build -t alberto1118/app-notas:1.0.0 .
      - name: Publicar la imagen a DockerHub
        run: docker push alberto1118/app-notas:1.0.0
        
        
  despliegue-app:
    needs: subirImagen
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: tfm-alberto-devops
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true