name: DevOps

on: [push, pull_request]

jobs:
  construirImagen:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
            version: v0.7.0
      - uses: docker/build-push-action@v2
        with:
          version: v0.7.0
          context: .
          tags: alberto1811/app-notas:latest
          push: false

  subirImagen:
    needs: construirImagen
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Loguarse a DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Subir imagen a DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: alberto1811/app-notas:latest
          push: true

  despliegue:
    needs: subirImagen
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: tfm-alberto-devops
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        usedocker: true
